"""order_model

Revision ID: f10eaf0a626a
Revises: 819cbf6e030b
Create Date: 2024-08-09 16:50:22.674279

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f10eaf0a626a"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_model",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dog_name", sa.String(length=200), nullable=False),
        sa.Column("room_number", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_model")
    # ### end Alembic commands ###
